name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # PMD analysis
      - uses: girishla/pmd-analyse@master
      - name: code-analysis-commons
        run: pmd -d uipath-commons/main/default/classes/ -R category/apex/design.xml -l apex -f text
